# Generated by Django 4.2.5 on 2023-10-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_chatparameter_guestuseraccount_delete_guestaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuseraccount',
            name='coins',
            field=models.IntegerField(default=10),
        ),
    ]
